package models

type FinalBatch struct {
	ResourceType  string `json:"resourceType"`
	ID            string `json:"id"`
	BatchID       string `json:"batchId"`
	Manufacturer  string `json:"manufacturer,omitempty"` // ClientID of manufacturer
	Org           string `json:"org,omitempty"`          // MSP org
	QuantityUnits int    `json:"quantityUnits,omitempty"`
	PackagingDate string `json:"packagingDate,omitempty"`
	QRPayload     string `json:"qrPayload,omitempty"` // QR payload generated by chaincode
	Timestamp     string `json:"timestamp,omitempty"` // When finalized
}
