################################################################################
# Hyperledger Fabric Peer Configuration File
################################################################################

# Peer identification
peer:
  id: peer0.org1.example.com
  networkId: dev
  address: localhost:7051
  localMspId: Org1MSP
  gossip:
    bootstrap: localhost:7051
    useLeaderElection: true
    orgLeader: false
    endpoint: localhost:7051
  listenAddress: 0.0.0.0:7051
  chaincodeListenAddress: 0.0.0.0:7052

# TLS configuration
tls:
  enabled: true
  cert:
    file: /etc/hyperledger/fabric/tls/server.crt
  key:
    file: /etc/hyperledger/fabric/tls/server.key
  rootcert:
    file: /etc/hyperledger/fabric/tls/ca.crt

# Local MSP path
mspConfigPath: ../crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp

# Ledger configuration
ledger:
  state:
    database: leveldb
  history:
    enableHistoryDatabase: false

# CouchDB (optional)
couchdb:
  address: localhost:5984
  username: ""
  password: ""

# Chaincode external builder / launcher settings
chaincode:
  externalBuilders: []

# Logging
logging:
  peer:
    level: info
