################################################################################
# Hyperledger Fabric Peer Configuration (core.yaml template)
################################################################################

peer:
  # Peer identity (overridden by env CORE_PEER_ID, CORE_PEER_ADDRESS, etc.)
  id: peer0.org.example.com
  networkId: dev
  address: 0.0.0.0:7051
  localMspId: OrgMSP

  # Gossip settings (auto-overridden by env vars in docker-compose)
  gossip:
    bootstrap: 127.0.0.1:7051
    useLeaderElection: true
    orgLeader: false
    endpoint: 127.0.0.1:7051

  listenAddress: 0.0.0.0:7051
  chaincodeListenAddress: 0.0.0.0:7052
  chaincodeAddress: 127.0.0.1:7052

# TLS configuration (mounted into container)
tls:
  enabled: true
  cert:
    file: /etc/hyperledger/fabric/tls/server.crt
  key:
    file: /etc/hyperledger/fabric/tls/server.key
  rootcert:
    file: /etc/hyperledger/fabric/tls/ca.crt

# Local MSP path (mounted in docker-compose)
mspConfigPath: /etc/hyperledger/fabric/msp

# Ledger configuration
ledger:
  state:
    database: goleveldb # change to couchdb if you enable it
  history:
    enableHistoryDatabase: true

# CouchDB (optional, used if CORE_LEDGER_STATE_DATABASE=couchdb)
couchdb:
  address: couchdb:5984
  username: ""
  password: ""

# Chaincode external builder / launcher settings
chaincode:
  externalBuilders: []
  installTimeout: 300s
  startuptimeout: 300s

# Logging
logging:
  peer:
    level: info
  gossip:
    level: info
  ledger:
    level: info
  msp:
    level: info
  policies:
    level: info
  grpc:
    level: error
