############################################################
# crypto-config.yaml for SupplyChain Network
############################################################

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Collectors
    Domain: collectors.example.com
    Template:
      Count: 1 # number of peers in this org
    Users:
      Count: 1 # number of client/admin users

  - Name: Farmers
    Domain: farmers.example.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Labs
    Domain: labs.example.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Processors
    Domain: processors.example.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Manufacturers
    Domain: manufacturers.example.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Provenance
    Domain: provenance.example.com
    Template:
      Count: 1
    Users:
      Count: 1
